# Copyright (c) 2019, Anders Lervik.
# Distributed under the MIT License. See LICENSE for more info.
"""Version information for normetapi.

This file is generated by the script ``setup_version.py``.
"""
SHORT_VERSION = '0.0.1'
VERSION = '0.0.1'
FULL_VERSION = '0.0.1'
GIT_REVISION = '5b604fb7b5e3ed2f341e371e751c4478f1cf45c4'
GIT_VERSION = '0.0.1'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
