# Copyright (c) 2021, Anders Lervik.
# Distributed under the MIT License. See LICENSE for more info.
"""Version information for normetapi.

This file is generated by normetapi (``setup_version.py``).
"""
SHORT_VERSION = '0.1.0'
VERSION = '0.1.0'
FULL_VERSION = '0.1.0'
GIT_REVISION = 'e96063555d6ff4ea5ee18af53b78d4633e9ed198'
GIT_VERSION = '0.1.0'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
